databases:
  - name: kijanikingadb
    plan: free
    databaseName: kijani_kinga
    user: kijani_admin

services:
  - type: web
    plan: free
    name: kijani-kinga
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kijanikingadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    